config:
  networks:
    mgmt:
      name: ""
      cidr: ""
      gateway: ""
    data:
      name: ""
      cidr: ""
    n3:
      name: ""
      cidr: ""
    n6:
      name: ""
      cidr: ""
    gnb:
      name: ""
      cidr: ""
    k8s_lb_ips: []
  vim:
    tenant: ""
    user: ""
    password: ""
    url: "http://os.maas:5000/v3"
