from .virtualization_provider_openstack import VirtualizationProviderOpenstack
from blueprints_ng.providers.virtualization.proxmox.virtualization_provider_proxmox import VirtualizationProviderProxmox
