{
 "title": "5G Network Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" },
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Connected UPFs",
   "type": "stat",
   "description": "Connected UPFs",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nf_status{nfType=\"UPF\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected GNBs",
   "type": "stat",
   "description": "Connected GNBs",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nf_status{nfType=\"GNB\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " PDU Sessions",
   "type": "stat",
   "description": "PDU Sessions",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "smf_pdu_sessions", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Connected Subscribers",
   "type": "table",
   "description": "5G Active PDU Sessions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "core_subscriber{}", "legendFormat": "__auto" }
   ]
  }
 ]
}