#!/usr/bin/env python3
"""
Generate _version.py file from git tags for Docker builds.

This script is used to create a version file that can be used when building
Docker images where the .git folder is not available. It reads the version
from git tags and generates src/nfvcl/_version.py.

Usage:
    python3 scripts/generate_version.py

This script should be run:
    - Before building Docker images locally (or use ./scripts/build_docker.sh)
    - In CI/CD pipelines before docker build (already configured in .gitlab-ci.yml)

The generated file is automatically used by hatch-vcs as a fallback when
git is not available (e.g., inside Docker containers).

Version format examples:
    - On a tagged commit (v0.4.1):          0.4.1
    - 5 commits after v0.4.1:               0.4.1.dev5+g1234abc
    - Tagged with v0.4.1-beta:              0.4.1
"""
import subprocess
import sys
from pathlib import Path


def get_version_from_git():
    """
    Get version from git describe command.

    This uses 'git describe' to find the most recent tag matching v[0-9]*
    and converts it to PEP 440 compatible version format.

    Returns:
        str: Version string in PEP 440 format, or None if git describe fails

    Examples:
        - v0.4.1          -> "0.4.1"
        - v0.4.1-5-g1abc  -> "0.4.1.dev5+g1abc" (5 commits after v0.4.1)
    """
    try:
        # Run git describe to get version from tags
        # --tags: Look for any tags matching the pattern
        # --match v[0-9]*: Only consider tags starting with 'v' followed by a number
        result = subprocess.run(
            ['git', 'describe', '--tags', '--match', 'v[0-9]*'],
            capture_output=True,
            text=True,
            check=True
        )
        version_str = result.stdout.strip()

        # Remove 'v' prefix from version string
        # v0.4.1 -> 0.4.1
        if version_str.startswith('v'):
            version_str = version_str[1:]

        # Convert git describe format to PEP 440 format
        # Git describe returns: <tag>-<commits-since-tag>-g<commit-hash>
        # We convert this to PEP 440: <version>.dev<commits>+g<hash>
        parts = version_str.split('-')

        if len(parts) == 1:
            # Clean tag with no commits after it
            # Example: "0.4.1"
            return parts[0]
        elif len(parts) >= 3:
            # Development version with commits after tag
            # Example: "0.4.1-5-g1234abc" -> "0.4.1.dev5+g1234abc"
            base_version = parts[0]      # "0.4.1"
            commits = parts[1]            # "5"
            commit_hash = parts[2]        # "g1234abc"
            return f"{base_version}.dev{commits}+{commit_hash}"
        else:
            # Unexpected format, return as-is
            return version_str

    except subprocess.CalledProcessError as e:
        # git describe failed - likely no tags exist
        print(f"Error: git describe failed: {e}", file=sys.stderr)
        print("", file=sys.stderr)
        print("This usually means no git tags exist in your repository.", file=sys.stderr)
        print("To fix this, create a tag with:", file=sys.stderr)
        print("  git tag v0.4.1", file=sys.stderr)
        print("  git push origin v0.4.1", file=sys.stderr)
        return None
    except FileNotFoundError:
        # git command not found
        print("Error: git command not found", file=sys.stderr)
        print("Make sure git is installed and available in PATH", file=sys.stderr)
        return None
    except Exception as e:
        # Unexpected error
        print(f"Error: Unexpected error occurred: {e}", file=sys.stderr)
        return None


def generate_version_file(version):
    """
    Generate the _version.py file with the given version.

    This creates src/nfvcl/_version.py with the version information that
    will be used by hatch-vcs when git is not available (e.g., in Docker).

    Args:
        version (str): Version string in PEP 440 format

    Returns:
        Path: Path to the generated version file
    """
    # Get project root directory (parent of scripts directory)
    project_root = Path(__file__).parent.parent
    version_file = project_root / "src" / "nfvcl" / "_version.py"

    # Create directory if it doesn't exist
    version_file.parent.mkdir(parents=True, exist_ok=True)

    # Parse version for version_tuple
    # Remove any +commit suffix and .devN suffix to get clean version
    # "0.4.1.dev5+g1234abc" -> "0.4.1"
    version_clean = version.split('+')[0].split('.dev')[0]
    version_parts = version_clean.split('.')

    # Generate the file content
    # This matches the format expected by setuptools and other tools
    content = f'''# File generated by scripts/generate_version.py
# Do not edit manually - this file is auto-generated from git tags
#
# To regenerate: python3 scripts/generate_version.py

__version__ = "{version}"
__version_tuple__ = {tuple(int(p) for p in version_parts[:3])}
'''

    # Write the file
    version_file.write_text(content)
    return version_file


def main():
    """Main entry point for the script."""
    print("=" * 60)
    print("Generating version file from git tags...")
    print("=" * 60)

    # Step 1: Get version from git
    version = get_version_from_git()
    if not version:
        print("\n❌ Failed to get version from git", file=sys.stderr)
        sys.exit(1)

    # Step 2: Generate the version file
    version_file = generate_version_file(version)

    # Step 3: Show success message
    try:
        # Try to show relative path from current directory
        relative_path = version_file.relative_to(Path.cwd())
        print(f"\n✓ Generated: {relative_path}")
    except ValueError:
        # If not in project directory, show absolute path
        print(f"\n✓ Generated: {version_file}")

    print(f"✓ Version: {version}")
    print("\n" + "=" * 60)
    print("You can now build the Docker image:")
    print("  docker build -t nfvcl .")
    print("Or use the build script:")
    print("  ./scripts/build_docker.sh")
    print("=" * 60)


if __name__ == "__main__":
    main()
